#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H

#include <vector>

/**
 * List of fixed seed nodes for the tyriancoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    // Uncomment and add seed nodes here
};

static SeedSpec6 pnSeed6_test[] = {
    // Uncomment and add seed nodes here
};

#endif // BITCOIN_CHAINPARAMSSEEDS_H

