#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H

#include <vector>

/**
 * List of fixed seed nodes for the phloxcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
<<<<<<< HEAD
    // Mainnet seed nodes
    {"149.28.46.22", 2333},  // Replace with your server instance IP and P2P port
    {"66.135.29.251", 2333}, // Replace with your server instance IP and P2P port
    {"45.63.107.24", 2333}   // Replace with your server instance IP and P2P port
};

static SeedSpec6 pnSeed6_test[] = {
    // Testnet seed nodes
=======
    // Uncomment and add seed nodes here
};

static SeedSpec6 pnSeed6_test[] = {
    // Uncomment and add seed nodes here
>>>>>>> 1a1bb180c044106f8705dabf8c504453b1b42883
};

#endif // BITCOIN_CHAINPARAMSSEEDS_H

